### ISSUE TITLE
404s on every path except 'metrics'

### ISSUE THREAD

**Issue by brianclemens** [fireeye/gocrack#45]
Built with Go 1.10.1 and Hashcat 3.6.0 on Arch Linux.  Everything appears to be working including worker authentication, except that I can't access the web interface itself:

#### gocrack_server log:
```
{"time":"2018-04-30T19:13:16+09:00","level":"info","addr":"[::]:1338","message":"HTTP Server listening"}
{"time":"2018-04-30T19:13:16+09:00","level":"info","addr":"[::]:1339","message":"RPC Server listening"}
{"time":"2018-04-30T19:13:42+09:00","level":"info","client_ip":"127.0.0.1","method":"POST","path":"/rpc/v1/beacon","status":200,"latency":"1.278765ms","message":"Processed HTTP 
Request"}
{"time":"2018-04-30T19:14:00+09:00","level":"info","client_ip":"153.222.[redacted]","method":"GET","path":"/","status":404,"latency":"402.028�s","message":"Processed HTTP Request"}
{"time":"2018-04-30T19:14:12+09:00","level":"info","client_ip":"127.0.0.1","method":"POST","path":"/rpc/v1/beacon","status":200,"latency":"950.842�s","message":"Processed HTTP 
Request"}
{"time":"2018-04-30T19:14:32+09:00","level":"info","client_ip":"153.222.[redacted]","method":"GET","path":"/metrics","status":200,"latency":"6.884966ms","message":"Processed HTTP 
Request"}
{"time":"2018-04-30T19:14:42+09:00","level":"info","client_ip":"127.0.0.1","method":"POST","path":"/rpc/v1/beacon","status":200,"latency":"408.585�s","message":"Processed HTTP 
Request"}
{"time":"2018-04-30T19:14:51+09:00","level":"info","client_ip":"153.222.[redacted]","method":"GET","path":"/","status":404,"latency":"460.473�s","message":"Processed HTTP Request"}
```

#### server.yaml
``` yaml
debug: true
web_server:
  listener:
    address: ":1338"
    ssl_enabled: false
  cors:
    allowed_origins:
        - "*"
  ui:
    csrf_key: [redacted]
    csrf_enabled: true
rpc_server:
  listener:
    address: ":1339"
    ssl_enabled: true
    ssl_ca_certificate: |
      -----BEGIN CERTIFICATE-----
      [redacted]
      -----END CERTIFICATE-----
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
     [redacted]
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      [redacted]
      -----END RSA PRIVATE KEY-----
database:
  backend: bdb
  connection_string: /home/oda/gocrack/server/database.db
file_manager:
  engine_file_path: /home/oda/gocrack/server/engine
  task_file_path: /home/oda/gocrack/server/task
  temp_path: /home/oda/gocrack/server/temp
  import_path: /home/oda/gocrack/server/import
authentication:
  backend: "database"
  secret_key: [redacted]
  backend_settings:
    bcrypt_cost: 10
    allow_registration: true
notifications:
  email_server:
    address: mail.teknik.io
  enabled: false
  from_address: gocrack@teknik.io
  public_address: http://crack.tiuxo.com:1338
```
