### ISSUE TITLE
Running the server container - Error

### ISSUE THREAD

**Issue by mdaugherty112** [fireeye/gocrack#47]
When I run the docker run -it for the server I get the following error:
Adding user `gocrack' ...
Adding new group `gocrack' (1000) ...
Adding new user `gocrack' (1000) with group `gocrack' ...
Creating home directory `/home/gocrack' ...
Copying files from `/etc/skel' ...
{"time":"2018-06-22T17:58:34Z","level":"fatal","error":"file_manager.task_file_path has to be a valid, writable folder","message":"Failed to initialize server"}

I know task_file_path is from the config file and has a value: /opt/gocrack_server/files/task
Any help would be appreciated.

**Comment by 0xIn7rud3r** [comment]
I faced this error. Make sure you have following directory structure created and write permissions assigned. 
```
opt/gocrack/
├── files
│   ├── engine
│   ├── import
│   ├── task
│   └── temp
```
Also following parameters in config.yaml file.

```
file_manager:
  engine_file_path: /opt/gocrack/files/engine
  task_file_path: /opt/gocrack/files/task
  import_path: /opt/gocrack/files/import
  temp_path: /opt/gocrack/files/temp
```

PS: Its recommended to keep base path as "/opt/gocrack/". if using different location you may need to edit it at few other places before build.
